# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5ioNIh1WmxuYIgrxlq2bwWBq2eBBdvg
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install "lightly-train[ultralytics]" "supervision==0.25.1"

from ultralytics.data.utils import check_det_dataset
dataset = check_det_dataset("HomeObjects-3K.yaml")

import random
import matplotlib.pyplot as plt
import supervision as sv
import yaml

from ultralytics import settings
from ultralytics.data.utils import check_det_dataset

dataset = check_det_dataset("HomeObjects-3K.yaml")

detections = sv.DetectionDataset.from_yolo(
    data_yaml_path=dataset["yaml_file"],
    images_directory_path=f"{settings['datasets_dir']}/homeobjects-3K/images/train/",
    annotations_directory_path=f"{settings['datasets_dir']}/homeobjects-3K/labels/train/"
)

# read class name
with open(dataset["yaml_file"], "r") as f:
    data = yaml.safe_load(f)
names = data["names"]

box_annotator = sv.BoxAnnotator()
label_annotator = sv.LabelAnnotator()

fig, ax = plt.subplots(2, 2, figsize=(10, 10))
ax = ax.flatten()

# select 4 images randomly
detections = [detections[random.randint(0, len(detections))] for _ in range(4)]

# processing and showing image
for i, (path, image, annotation) in enumerate(detections):
    annotated_image = box_annotator.annotate(scene=image, detections=annotation)
    annotated_image = label_annotator.annotate(
        scene=annotated_image,
        detections=annotation,
        labels=[names[elem] for elem in annotation.class_id],
    )
    ax[i].imshow(annotated_image[..., ::-1])
    ax[i].axis("off")

plt.tight_layout()
plt.show()

!ls "/content/drive/MyDrive/Glom/Dinov3"

import lightly_train
from ultralytics import settings
data_path = f"{settings['datasets_dir']}/homeobjects-3K/images/train"

if __name__ == "__main__":
    lightly_train.train(
        out="out/my_experiment",
        data=data_path,
        overwrite=True,
        model="ultralytics/yolo11s.yaml",
        method="distillation",
        method_args={
            "teacher": "dinov3/vits16",
            # Replace with your own url
            "teacher_url": "/content/drive/MyDrive/Glom/Dinov3/dinov3_vits16_pretrain_lvd1689m-08c60483.pth",
        }
    )

from ultralytics import YOLO

if __name__ == "__main__":
    # Load the exported model.
    model = YOLO("/content/out/my_experiment/exported_models/exported_last.pt")

    # Fine-tune with ultralytics.
    model.train(data = '/content/dataset/homeobjects-3K/HomeObjects-3K.yaml', epochs=50)